export const array=[
      {
        l:'https://i.gadgets360cdn.com/large/mi_gaming_laptop_2019_image_1565003115644.jpg',
      name:'Hp'
      },
      {
        l:'https://cdn.mos.cms.futurecdn.net/vEcELHdn998wRTcCzqV5m9.jpg',
      name:'Hp'
      },
      {
        l:'https://cdn.mos.cms.futurecdn.net/6t8Zh249QiFmVnkQdCCtHK.jpg',
      name:'Hp'
      },
      {
        l:'https://images-na.ssl-images-amazon.com/images/I/71h6PpGaz9L._AC_SL1500_.jpg',
      name:'Mac'
      },
      {
        l:'https://images-na.ssl-images-amazon.com/images/I/81SdJG3OUjL._SL1500_.jpg',
      name:'Mac'
      },
      {
        l:'https://images.anandtech.com/doci/15680/Swift-3_SF314-42_front-facing.jpg',
      name:'Dell'
      },
      {
        l:'https://cdn.thewirecutter.com/wp-content/uploads/2020/04/laptops-lowres-2x1--1024x512.jpg',
      name:'Dell'
      },
      {
        l:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4pbaQaHlqJ5wdt300ROAooeuyOX-vLxipcg&usqp=CAU',
      name:'Asus'
      },
      {
        l:'https://cdn.mos.cms.futurecdn.net/fQ3rjuW46d9rGAZRoanXdK-1200-80.jpg',
      name:'Asus'
      },
      {
        l:'https://img.etimg.com/photo/msid-74744213,quality-100/hp-14q-cy0005au.jpg',
      name:'Acer'
      },
      {
        l:'https://i.ytimg.com/vi/U-9tUEOFKNU/maxresdefault.jpg',
      name:'Acer'
      },
      {
        l:'https://media.wired.com/photos/5fb6da7980c372e180a889b8/191:100/w_2291,h_1199,c_limit/Laptops.png',
      name:'Xebronics'
      },
      {
        l:'https://www.lenovo.com/medias/lenovo-laptop-legion-5-15-amd-subseries-hero.png?context=bWFzdGVyfHJvb3R8MTY1MTc2fGltYWdlL3BuZ3xoMGEvaGU4LzEwODM3OTM5NjE3ODIyLnBuZ3xiNjNmYTE3M2M2NGY5YjljMmI3ZjhkMmJjYTBmYjkzZDM1MDRhY2QwOTVlODViYTVlZjQyMTljNjE1ODY0ZTNj',
      name:'Acer'
      },
      {
        l:'https://cdn.mos.cms.futurecdn.net/6t8Zh249QiFmVnkQdCCtHK.jpg',
      name:'Lenovo'
      },
      {
        l:'https://cdn.mos.cms.futurecdn.net/6t8Zh249QiFmVnkQdCCtHK.jpg',
      name:'Lenovo'
      }
];
